version: '3.8'

services:
  firebase-boilerplate:
    container_name: firebase-boilerplate
    restart: unless-stopped
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - ./.env.local
    networks:
      - mydockernet

networks:
  mydockernet:
    driver: bridge
